<a href="https://colab.research.google.com/github/vlokhande39/tensorflow1/blob/main/basic_tensors_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic Tensors operations
-tensor is a n dimensional array of data

In [ ]:
import tensorflow as tf

In [ ]:
#initialization of tensorflow
x = tf.constant(4) #creating a single nu of tensor
print(x)

x1 = tf.constant(4.0,shape=(1,1))#we can assign a shape
print(x1)

x2 = tf.constant(4,shape=(1,1), dtype="float32")#we can give the datatype to the tensor
print(x2)

x3 = tf.constant([[1,2,3],[4,5,6]])
print(x3)

x4= tf.ones((3,3))
print(x4)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
x5 = tf.zeros((2,3)) #creating a zeros matrix which is 2 by 3
print(x5)

x6 = tf.eye(4) #identity matrix of 4-rows and 4-col
print(x6)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [ ]:
x7 = tf.random.normal((3,3), mean=0, stddev=1) #creating a tensor with -1 to 1 range of distributions
print(x7)

x8 = tf.random.uniform((2,3), minval = 1, maxval=5) #uniform dit. tensor with the min value is 1 and max value is 5
print(x8)

x9 = tf.range(9)
print(x9)

x10 = tf.range(start=1, limit=10, delta=2) #creating a tensor a like start from 1 and limit means end to 10, and the steps it take as 2
print(x10)
#we can change the data type of the tensor
x10 = tf.cast(x10,dtype="float64")
print(x10)

tf.Tensor(
[[ 0.73386323 -1.5232878   0.5710439 ]
 [-0.7550891   1.5444793  -0.29661912]
 [-0.3386282   1.4832234   0.24345927]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1.9513283 1.470676  3.5095406]
 [1.7508388 2.5139556 4.618115 ]], shape=(2, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [ ]:
#mathematical operations
a = tf.constant([1,2,3])
b = tf.constant([9,8,7])
z = tf.add(a,b) #z = a+b
print(z)

z1 = tf.subtract(a,b) #z1 = a-b
print(z1)

z2 = tf.divide(a,b) # z2 = a/b
print(z2)

z3 = tf.multiply(a,b) # z3 = a*b
print(z3)

z4 = tf.tensordot(a,b, axes=1)
print(z4)
z4 = tf.tensordot(a,b, axes=0)
print(z4)

z5 = a ** 5 # its just like 1^5, 2^5, 3^5
print(z5)

#matrix multiplication
v = tf.random.normal((2,3))
u = tf.random.normal((3,4))
print(v)
print(u)
z6 = tf.matmul(v,u)
print(z6)
print(v @ u) #both are doing same operations


tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0.60410774  0.70117253  0.7329451 ]
 [-1.4088696  -0.59408367  2.163484  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.5663011   0.8120568  -0.04453919 -2.8746526 ]
 [ 1.8126156   2.043417    0.08288058  0.41246757]
 [ 0.5526243   0.44084102  0.5273858  -0.41925338]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 2.6222143  2.24647    0.4177519 -1.7546787]
 [-2.0879655 -1.4042902  1.1545026  2.8979225]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 2.6222143  2.24647    0.4177519 -1.7546787]
 [-2.0879655 -1.4042902  1.1545026  2.8979225]], shape=(2, 4), dtype=float32)


In [ ]:
#indexing of tensor
s = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(s[:])#printing all the element
print(s[1:]) #start from 1index to all
print(s[1:3]) # start form 1 to end index-1
print(s[::-1]) #reverse order

#we can print the multiple value of index given indexes
indices = tf.constant([1,4,5]) # 1,4 and 5 indexes values
s_inx = tf.gather(s, indices)
print(s_inx)  

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 3 1], shape=(3,), dtype=int32)


In [ ]:
#basic reshaping of index
d = tf.range(9)
print(d)
d1 = tf.reshape(d , (3,3))
print(d1)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
